[package]
name = "school-helper"
version = "0.1.0"
authors = ["Niki Hellmers <nihe1661@colorado.edu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"